### ISSUE TITLE
Submitting Data to table and sending back edited table to Node Red

### ISSUE THREAD

**Issue by ConBeeUser** [Gippsman2017/node-red-node-ui-etable#1]
Hi Gippsman,

how do I send data (json?) to the table? I've set up columns and options and tried to send a json-payload to the node but nothing happens. 

There are several fanatastic examples on tabulator.info . But at the moment I cannot interact with the table as is doesn't have any data in it.
Would you mind giving me a hint? I can imagine a few usecases for this node ;-)

In the long run, it would be great if you provided examples in the sample section of Node Red.

Thank you for this great node!

Best regards
ConBeeUser

**Comment by Gippsman2017** [comment]
Hi ConBeeUser, 

Sorry about the docs, Yes, I was in a rush to get
this out as my team needed it, ts fairly straight forward, the
msg.payload object names must match the field names in the etable node.


Try this flow 

[{"id":"7f7c6824.54e94","type":"tab","label":"Etable
Test","disabled":false,"info":""},{"id":"ee24aebb.54f0e8","type":"ui_etable","z":"7f7c6824.54e94","payload":"[{"title":"PushMe","field":"PushMe","width":"10%","editor":false},{"title":"My
Field A","field":"a","width":"80%","editor":true},{"title":"My Field A
-
Type","field":"b","editor":"select","editorParams":{"values":["NEW","UPDATED","CANCELED"]}}]","payloadType":"json","options":"{"movableColumns":true,"layout":"fitColumns","pagination":"local","height":"700px"}","group":"81b1bfdb.4662f8","name":"","order":2,"width":"20","height":"7","columns":[],"outputs":1,"cts":false,"x":690,"y":180,"wires":[["db83b4fb.4adf48","8fa2d566.9b9528"]]},{"id":"861cc629.8485","type":"inject","z":"7f7c6824.54e94","name":"","topic":"","payload":"{"a":"wombat","b":"NEW"}","payloadType":"json","repeat":"","crontab":"","once":true,"onceDelay":0.1,"x":390,"y":260,"wires":[["5cc9caef.b0116c","c2f61254.095ab8"]]},{"id":"db83b4fb.4adf48","type":"debug","z":"7f7c6824.54e94","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":890,"y":120,"wires":[]},{"id":"5cc9caef.b0116c","type":"debug","z":"7f7c6824.54e94","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"tru
 e","targ
etType":"full","x":570,"y":340,"wires":[]},{"id":"c2f61254.095ab8","type":"function","z":"7f7c6824.54e94","name":"","func":"var
a1 = '12345';nvar a2 = 'ABCDE';nnmsg.payload = [n{ "PushMe":"a1", "a" :
a1, "b" : 'NEW' },n{ "PushMe":"a2", "a" : a2, "b" : 'UPDATE' }];nreturn
msg;","outputs":1,"noerr":0,"x":530,"y":200,"wires":[["ee24aebb.54f0e8"]]},{"id":"8fa2d566.9b9528","type":"ui_text","z":"7f7c6824.54e94","group":"81b1bfdb.4662f8","order":2,"width":"8","height":"3","name":"","label":"text","format":"{{msg.payload}}","layout":"row-spread","x":1020,"y":220,"wires":[]},{"id":"81b1bfdb.4662f8","type":"ui_group","z":"","name":"test","tab":"700e0299.f39d8c","order":1,"disp":true,"width":"20","collapse":false},{"id":"700e0299.f39d8c","type":"ui_tab","z":"","name":"Home","icon":"dashboard","disabled":false,"hidden":false}]


Cheers 

Gippsman2017 

On 2019-12-05 2:51, ConBeeUser wrote: 

> Hi
Gippsman, 
> 
> how do I send data (json?) to the table? I've set up
columns and options and tried to send a json-payload to the node but
nothing happens. 
> 
> There are several fanatastic examples on
tabulator.info . But at the moment I cannot interact with the table as
is doesn't have any data in it.
> Would you mind giving me a hint? I can
imagine a few usecases for this node ;-) 
> 
> In the long run, it would
be great if you provided examples in the sample section of Node Red. 
>

> Thank you for this great node! 
> 
> Best regards
> ConBeeUser 
> 
>
--
> You are receiving this because you are subscribed to this thread.
>
Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
!DSPAM:5de7d612149115565413645!

 

Links:
------
[1]
https://github.com/Gippsman2017/node-red-node-ui-etable/issues/1?email_source=notifications&amp;email_token=AGELCQ5TQNT2S74ORZ5GZE3QW7GY7A5CNFSM4JVKYHDKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4H6BPFNQ
[2]

**Comment by Gippsman2017** [comment]
I have submitted an example flow in the Node-Red flows library
