### ISSUE TITLE
etable.html does not exist

### ISSUE THREAD

**Issue by HaunsTM** [Gippsman2017/node-red-node-ui-etable#12]
Have installed node-red-node-ui-etable 1.0.4 in Home Assistant node red module.

Unfortunately, something seems to be missing:
![image](https://user-images.githubusercontent.com/10531742/95768383-88955000-0cb6-11eb-81aa-71d483b92b23.png)

**Comment by Gippsman2017** [comment]
No a fault, this node had been deprecated, please read the readme
