### ISSUE TITLE
Adding new / updating Rows (runtime)

### ISSUE THREAD

**Issue by tsprivate** [Gippsman2017/node-red-node-ui-etable#2]
Great work in getting this into Node-Red.  I have a few static tables but now i want
1) Add new rows to the table (keep existing table valid)
2) Modifying a certain value/row

How can I achieve that in Node-Red

**Comment by Gippsman2017** [comment]
OK, so from the two questions, as follows.
New rows are a table refresh, this can be achieved by using something like doing a select on an alasql-nr table and inserting rows and then doing a full select on the table to cause an update, also a way of selecting the row is by using "context menu" to write to the table.

If I get time, I will create a demo flow you can modify for your own uses.

I plan on releasing an update that has more functionality asap, however is needs to use mdashboard to utilise some of the new stuff as the current node-red-dashboard does not provide anything other than communal capabilities.

**Comment by Gippsman2017** [comment]
Hi tsprivate, I have added 2. above in V0.1.5
