### ISSUE TITLE
Getting selected or updated return  row into msg.payload

### ISSUE THREAD

**Issue by tsprivate** [Gippsman2017/node-red-node-ui-etable#3]
I'm using your table to display various sensors. I would now wanna get some return values from the table like
- Selected row (e.g. entire row as object)
- Updated row (e.g. changed element like enabled/disabled)

this would make the table much more interactive

thanks for considering

**Comment by Gippsman2017** [comment]
Hi tsprivate, 

To get the row back, the editor=false must be set,
otherwist it thinks that you are simply editing the value, as I have
said on the git page, I will create a flow that you can play around
with. 

It will become very obvious once you have something to play
around with. 

Cheers 

On 2019-12-22 17:11, tsprivate wrote: 

> I'm
using your table to display various sensors. I would now wanna get some
return values from the table like 
> 
> * Selected row (e.g. entire row
as object)
> * Updated row (e.g. changed element like
enabled/disabled)
> 
> this would make the table much more interactive

> 
> thanks for considering 
> 
> --
> You are receiving this because
you are subscribed to this thread.
> Reply to this email directly, view
it on GitHub [1], or unsubscribe [2]. !DSPAM:5dff091c310092903954339!




Links:
------
[1]
https://github.com/Gippsman2017/node-red-node-ui-etable/issues/3?email_source=notifications&amp;email_token=AGELCQ3AAVC2LU3SG55GBITQZ4AJPA5CNFSM4J6KLCDKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4ICFJ4RA
[2]
