### ISSUE TITLE
Not an issues but a query.  output response

### ISSUE THREAD

**Issue by nosaj66au** [Gippsman2017/node-red-node-ui-etable#5]
Can I pass a message to command an output response similar to what is generated when a mouse click occurs?  if so what is the format?

Regards 
Jason

**Comment by Gippsman2017** [comment]
Hi Jason,
If I get what is beneath your question, if the editable field flag is true, then it generally doesnt output the row, what you have to do is click on a field where it is set to false.
Cheers

**Comment by bjobo** [comment]
Hi Gippsman,

great work!
A follow up to Jasons question: Is there a way to output the result (in the flow) after I edited a field and did hit enter (or selected another editable field)?

Regards
Bjoern

**Comment by Gippsman2017** [comment]
Hi Jason, bjobo,
I have added the capability to both wanted in v0.1.5
Cheers
Gippsman2017
