### ISSUE TITLE
Please consider node-red-contrib naming

### ISSUE THREAD

**Issue by knolleary** [Gippsman2017/node-red-node-ui-etable#7]
Hi there - thanks for creating a node and sharing it with the community.

One request - as per our [packaging guidelines](http://nodered.org/docs/creating-nodes/packaging), we ask that 3rd party nodes use the `node-red-contrib-` prefix to their name. This ensures they don't get mistaken for nodes maintained by the project itself.

You're under no obligation to change the name, but I hope you'll consider it.

Many thanks, Nick

**Comment by Gippsman2017** [comment]
Hi Nick, 

I will work out a way of changing it without breaking
stuff, was running at breakneck speed and it was a lapse of naming
judgment !!! 

Sorry about that. 

Cheers 

John 

On 2020-03-04 22:13,
knolleary wrote: 

> Hi there - thanks for creating a node and sharing
it with the community. 
> 
> One request - as per our packaging
guidelines [1], we ask that 3rd party nodes use the node-red-contrib-
prefix to their name. This ensures they don't get mistaken for nodes
maintained by the project itself. 
> 
> You're under no obligation to
change the name, but I hope you'll consider it. 
> 
> Many thanks, Nick

> 
> --
> You are receiving this because you are subscribed to this
thread.
> Reply to this email directly, view it on GitHub [2], or
unsubscribe [3]. !DSPAM:5e5f8d4c239282847416338!

 

Links:
------
[1]
http://nodered.org/docs/creating-nodes/packaging
[2]
https://github.com/Gippsman2017/node-red-node-ui-etable/issues/7?email_source=notifications&amp;email_token=AGELCQ53LSJ7ZFGU6KJB5M3RFYZUPA5CNFSM4LBDKFU2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4ISKVWSA
[3]

**Comment by Gippsman2017** [comment]
Hi Nick,
I have now called it node-red-contrib-ui-etable
Cheers
John
